---
# tasks file for openvpn - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ openvpn_app }}
  apt:
    name: "{{ openvpn_app }}"
    state: "{{ openvpn_desired_state }}"
    force_apt_get: yes
    update_cache: yes
